{{- if .Values.chromadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workflow-builder.fullname" . }}-chromadb
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: chromadb
spec:
  replicas: {{ .Values.chromadb.replicaCount }}
  selector:
    matchLabels:
      {{- include "workflow-builder.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chromadb
  template:
    metadata:
      labels:
        {{- include "workflow-builder.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chromadb
    spec:
      containers:
        - name: chromadb
          image: "{{ .Values.chromadb.image.repository }}:{{ .Values.chromadb.image.tag }}"
          imagePullPolicy: {{ .Values.chromadb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: CHROMA_SERVER_HOST
              value: "0.0.0.0"
            - name: CHROMA_SERVER_HTTP_PORT
              value: "8001"
          {{- if .Values.chromadb.persistence.enabled }}
          volumeMounts:
            - name: chromadb-storage
              mountPath: /chroma/chroma
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.chromadb.resources | nindent 12 }}
      {{- if .Values.chromadb.persistence.enabled }}
      volumes:
        - name: chromadb-storage
          persistentVolumeClaim:
            claimName: {{ include "workflow-builder.fullname" . }}-chromadb-pvc
      {{- end }}
---
{{- if .Values.chromadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workflow-builder.fullname" . }}-chromadb-pvc
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.chromadb.persistence.size }}
  {{- if .Values.chromadb.persistence.storageClass }}
  storageClassName: {{ .Values.chromadb.persistence.storageClass }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-builder.fullname" . }}-chromadb-service
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chromadb.service.type }}
  ports:
    - port: {{ .Values.chromadb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workflow-builder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chromadb
{{- end }}