apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow-builder.fullname" . }}-secret
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
type: Opaque
data:
  API_SECRET_KEY: {{ .Values.secrets.apiSecretKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}