apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-builder.fullname" . }}-backend-service
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "workflow-builder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-builder.fullname" . }}-frontend-service
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "workflow-builder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend