apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workflow-builder-prod

resources:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend
    namespace: workflow-builder-prod
  spec:
    replicas: 3
    template:
      spec:
        containers:
        - name: backend
          image: workflow-backend:prod
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend
    namespace: workflow-builder-prod
  spec:
    replicas: 3
    template:
      spec:
        containers:
        - name: frontend
          image: workflow-frontend:prod
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres
    namespace: workflow-builder-prod
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

commonLabels:
  environment: production