apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: workflow-builder
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: workflow-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: DATABASE_URL
        - name: CHROMA_HOST
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: CHROMA_HOST
        - name: CHROMA_PORT
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: CHROMA_PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: REDIS_URL
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: API_SECRET_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: workflow-builder
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP