apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres.yaml
- chromadb.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml

commonLabels:
  app: workflow-builder
  version: v1.0.0