apiVersion: v2
name: workflow-builder
description: A Helm chart for Workflow Builder Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - workflow
  - ai
  - knowledge-base
  - react
  - fastapi
home: https://github.com/your-org/workflow-builder-app
sources:
  - https://github.com/your-org/workflow-builder-app
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled